# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-16 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_principal', models.CharField(max_length=50)),
                ('texto_secundario', models.CharField(max_length=50)),
                ('imagem', models.ImageField(blank=True, help_text='Aceita qualquer imagem sem espaço e caracteres especiais.<br>Tamanho recomendado 400x362.', null=True, upload_to='')),
                ('ativo', models.BooleanField(default=0)),
            ],
        ),
    ]
