# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-16 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170716_0951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='texto_primario',
            new_name='texto_1',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='texto_secundario',
            new_name='texto_2',
        ),
    ]
