# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-16 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20170716_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='texto_3',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
