# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-16 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_home_texto_3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duvida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('celular', models.IntegerField(help_text='ddd + celular')),
                ('mensagem', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='home',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Aceita qualquer imagem sem espaço e caracteres especiais.                          <br>Tamanho recomendado 400x362.', null=True, upload_to='home/'),
        ),
    ]
